### ISSUE TITLE
Some Problem :(

### ISSUE THREAD

**Issue by Claudfa** [festivaldev/dropshot#16]
This is how it happens when you enter the game after uberstrike comes to the user screen, how do I add a server.
![resim_2020-12-22_215803](https://user-images.githubusercontent.com/76493967/102923462-d8f01180-44a0-11eb-801d-a117ac2e0d92.png)

**Comment by vainamov** [comment]
You cannot play out-of-the-box on servers using Dropshot. Dropshots only purpose is to emulate all neccessary services in order to be able to start the game. A seperate game server running on the Photon architecture is needed to play actual games with other players. Unfortunately however, we never successfully finished one. It has been proven possible though, massive shoutout to https://github.com/FICTURE7 and his https://github.com/FICTURE7/uberstrok project. If you want to try it for yourself I suggest you check out uberstrok instead.
